pipeline {
    agent any

    tools {
        jdk 'jdk21'
        maven 'maven-3.9'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Vishwanth-Talluri/demo.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
    }
}
